### ISSUE TITLE
Installation fails for fresh Arduino 2.0

### ISSUE THREAD

**Issue by kgh-85** [cschorn01/2.4GHz_Lora_for_Arduino#1]
Installation fails for fresh Arduino 2.0:
"Failed to install library: 'sx1280OverSpi:1.1.0'. No valid dependencies solution found: dependency 'SPI' is not available"

**Comment by kgh-85** [comment]
When installing the Arduino Library from downloaded .zip it works.

**Comment by cschorn01** [comment]
Yup it's been giving me issues and I am not sure why. I followed the Arduino guide to creating a library and checked some libraries that are working and I changed my #includes but it's still not working.

I'll be looking more later today.

**Comment by cschorn01** [comment]
oops didnt mean to close it

**Comment by cschorn01** [comment]
The latest release was v1.1.0 which did not have the changed #includes. Just changed it to v1.1.1 with the changed #include statements. Will test when it is updated in the IDE

**Comment by cschorn01** [comment]
Took out the "depends" line from library.properties. Not sure why that's what broke it but it can be downloaded and used from the Arduino IDE without having to use a Zip.

**Comment by cschorn01** [comment]
Can you confirm the newest version works for you kgh-85? If it does I will close this issue.

**Comment by kgh-85** [comment]
Yes, works now thanks.
